### ISSUE TITLE
feat: Back-end 개발

### ISSUE THREAD

**Issue by Yewon-dev** [boostcampaitech3/final-project-level3-cv-02#33]
담당자 : @Yewon-dev 

- [x] FastAPI(BE)와 React(FE) 연결
- [x] GCS 연결
- [x] DB 연결
- [x] Inference 연결
- [x] 결과 이메일로 내보내기
- [x] 배포

**Comment by nestiank** [comment]
배포 완료를 확인했습니다.
수요일 오후에 커넥트재단의 GPU 서버 제공이 중단되기 때문에, 논의한 대로, 배포 URL은 공개하지 않기로 합니다.
이슈의 모든 subtask가 완료되었으므로, 메모를 남기고 이슈를 닫습니다.
